### ISSUE TITLE
Issue with module resolution in 0.1.2

### ISSUE THREAD

**Issue by peterlazar1993** [OP-Engineering/op-s2#5]
On installing 0.1.2 version of op-s2 vscode suddenly starts complaining.
<img width="841" alt="Screenshot 2024-05-02 at 14 16 57" src="https://github.com/OP-Engineering/op-s2/assets/4848554/fcb3d75b-e804-4b0e-b293-10b877faeb45">

On downgrading to 0.1.1 the problem goes away. This is baffling since I see no commits between these 2 versions which could cause this.
Was something changed in the way the module is published?

Repro here 
- https://github.com/peterlazar1993/NewProject/tree/main
- https://github.com/peterlazar1993/NewProject/tree/op-s2/0.1.1

**Comment by peterlazar1993** [comment]
<img width="899" alt="Screenshot 2024-05-02 at 16 56 54" src="https://github.com/OP-Engineering/op-s2/assets/4848554/8ec718a0-a2fa-425c-a8be-2f6f9a267d75">

Just running tsc errors out as well

**Comment by ospfranco** [comment]
I can reproduce it. And yeah, there are no changes. Maybe I botched the release somehow.

**Comment by ospfranco** [comment]
Should be fixed now (0.1.7), I re-added the build preparation step. Shouldn't be necessary but at least it works.
